Add map, filter and flatMap operators to Observable
UrbanCompass/Snail pull request #147
Opened 2020-11-24 23:05 UTC by luispadron

This PR aims to add some needed functionality to Snail. As well as cleans up some of the API.

Currently Observable type doesn't support, mapping, filtering or creating other observables.

This PR adds:

- `map` function to `Observable`
- `filter`﻿function to `Observable`
- `flatMap` function to `Observable`
- Adds `combineLatest` for 3 and 4 observables.
- Tests for the above

2020-11-24 23:06 UTC, luispadron commented on Package.swift
> +    ],
This was missing, let me know if the platform versions are correct here.

2020-11-30 16:20 UTC, luispadron commented
Not sure what else i can test to fix the coverage 🤷🏼

2020-11-30 16:20 UTC, russellbstephens commented on Snail/Observable.swift
> +    private func performBlock(timeout: TimeInterval?) -> (result: T?, error: Error?) {
should we leverage Swift.Result here?

2020-11-30 16:21 UTC, russellbstephens commented on Snail/Observable.swift
> +        // swiftlint:disable:next large_tuple
lets disable in the yml

2020-11-30 16:21 UTC, russellbstephens commented on Snail/Observable.swift
> +    public static func combineLatest<U, V>(
inconsistent codestyle

2020-11-30 16:22 UTC, russellbstephens requested changes
update README

2020-11-30 16:53 UTC, akun1 approved these changes

2020-11-30 18:02 UTC, merged